/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 25
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_COMMA = 3,
  anon_sym_setSink = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_transitive = 7,
  anon_sym_sanitize = 8,
  anon_sym_swapTaint = 9,
  anon_sym_LT = 10,
  anon_sym_DASH1 = 11,
  anon_sym_0 = 12,
  anon_sym_1 = 13,
  anon_sym_2 = 14,
  anon_sym_3 = 15,
  anon_sym_4 = 16,
  anon_sym_5 = 17,
  anon_sym_6 = 18,
  anon_sym_7 = 19,
  anon_sym_8 = 20,
  anon_sym_9 = 21,
  anon_sym_GT = 22,
  sym_taint_summary = 23,
  sym_side_effects = 24,
  sym_side_effects_tail = 25,
  sym_taint_side_effect = 26,
  sym_key = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_setSink] = "setSink",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_transitive] = "transitive",
  [anon_sym_sanitize] = "sanitize",
  [anon_sym_swapTaint] = "swapTaint",
  [anon_sym_LT] = "<",
  [anon_sym_DASH1] = "-1",
  [anon_sym_0] = "0",
  [anon_sym_1] = "1",
  [anon_sym_2] = "2",
  [anon_sym_3] = "3",
  [anon_sym_4] = "4",
  [anon_sym_5] = "5",
  [anon_sym_6] = "6",
  [anon_sym_7] = "7",
  [anon_sym_8] = "8",
  [anon_sym_9] = "9",
  [anon_sym_GT] = ">",
  [sym_taint_summary] = "taint_summary",
  [sym_side_effects] = "side_effects",
  [sym_side_effects_tail] = "side_effects_tail",
  [sym_taint_side_effect] = "taint_side_effect",
  [sym_key] = "key",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_setSink] = anon_sym_setSink,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_transitive] = anon_sym_transitive,
  [anon_sym_sanitize] = anon_sym_sanitize,
  [anon_sym_swapTaint] = anon_sym_swapTaint,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_DASH1] = anon_sym_DASH1,
  [anon_sym_0] = anon_sym_0,
  [anon_sym_1] = anon_sym_1,
  [anon_sym_2] = anon_sym_2,
  [anon_sym_3] = anon_sym_3,
  [anon_sym_4] = anon_sym_4,
  [anon_sym_5] = anon_sym_5,
  [anon_sym_6] = anon_sym_6,
  [anon_sym_7] = anon_sym_7,
  [anon_sym_8] = anon_sym_8,
  [anon_sym_9] = anon_sym_9,
  [anon_sym_GT] = anon_sym_GT,
  [sym_taint_summary] = sym_taint_summary,
  [sym_side_effects] = sym_side_effects,
  [sym_side_effects_tail] = sym_side_effects_tail,
  [sym_taint_side_effect] = sym_taint_side_effect,
  [sym_key] = sym_key,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_setSink] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_transitive] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sanitize] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_swapTaint] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_0] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_1] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_3] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_4] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_5] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_6] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_7] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_8] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_9] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_taint_summary] = {
    .visible = true,
    .named = true,
  },
  [sym_side_effects] = {
    .visible = true,
    .named = true,
  },
  [sym_side_effects_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_taint_side_effect] = {
    .visible = true,
    .named = true,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      ADVANCE_MAP(
        '(', 35,
        ')', 36,
        ',', 33,
        '-', 1,
        '0', 42,
        '1', 43,
        '2', 44,
        '3', 45,
        '4', 46,
        '5', 47,
        '6', 48,
        '7', 49,
        '8', 50,
        '9', 51,
        '<', 40,
        '>', 52,
        's', 4,
        't', 22,
        '{', 31,
        '}', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '1') ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == 'S') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'T') ADVANCE(7);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'w') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(21);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(37);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 12:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'i') ADVANCE(19);
      END_STATE();
    case 14:
      if (lookahead == 'i') ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'k') ADVANCE(34);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 20:
      if (lookahead == 'n') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'p') ADVANCE(3);
      END_STATE();
    case 22:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(15);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(2);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(39);
      END_STATE();
    case 26:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(11);
      END_STATE();
    case 28:
      if (lookahead == 'v') ADVANCE(9);
      END_STATE();
    case 29:
      if (lookahead == 'z') ADVANCE(8);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_setSink);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_transitive);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_sanitize);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_swapTaint);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH1);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_0);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_1);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_3);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_4);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_5);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_6);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_7);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_8);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_9);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_setSink] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_transitive] = ACTIONS(1),
    [anon_sym_sanitize] = ACTIONS(1),
    [anon_sym_swapTaint] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_DASH1] = ACTIONS(1),
    [anon_sym_0] = ACTIONS(1),
    [anon_sym_1] = ACTIONS(1),
    [anon_sym_2] = ACTIONS(1),
    [anon_sym_3] = ACTIONS(1),
    [anon_sym_4] = ACTIONS(1),
    [anon_sym_5] = ACTIONS(1),
    [anon_sym_6] = ACTIONS(1),
    [anon_sym_7] = ACTIONS(1),
    [anon_sym_8] = ACTIONS(1),
    [anon_sym_9] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_taint_summary] = STATE(13),
    [anon_sym_LBRACE] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(5), 11,
      anon_sym_DASH1,
      anon_sym_0,
      anon_sym_1,
      anon_sym_2,
      anon_sym_3,
      anon_sym_4,
      anon_sym_5,
      anon_sym_6,
      anon_sym_7,
      anon_sym_8,
      anon_sym_9,
  [14] = 5,
    ACTIONS(7), 1,
      anon_sym_RBRACE,
    STATE(5), 1,
      sym_taint_side_effect,
    STATE(16), 1,
      sym_side_effects,
    ACTIONS(9), 2,
      anon_sym_setSink,
      anon_sym_sanitize,
    ACTIONS(11), 2,
      anon_sym_transitive,
      anon_sym_swapTaint,
  [32] = 3,
    STATE(6), 1,
      sym_taint_side_effect,
    ACTIONS(9), 2,
      anon_sym_setSink,
      anon_sym_sanitize,
    ACTIONS(11), 2,
      anon_sym_transitive,
      anon_sym_swapTaint,
  [44] = 3,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    STATE(22), 1,
      sym_side_effects_tail,
  [54] = 3,
    ACTIONS(15), 1,
      anon_sym_COMMA,
    ACTIONS(17), 1,
      anon_sym_RBRACE,
    STATE(21), 1,
      sym_side_effects_tail,
  [64] = 2,
    ACTIONS(19), 1,
      anon_sym_LT,
    STATE(20), 1,
      sym_key,
  [71] = 2,
    ACTIONS(19), 1,
      anon_sym_LT,
    STATE(19), 1,
      sym_key,
  [78] = 1,
    ACTIONS(21), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [83] = 2,
    ACTIONS(19), 1,
      anon_sym_LT,
    STATE(24), 1,
      sym_key,
  [90] = 1,
    ACTIONS(23), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [95] = 1,
    ACTIONS(25), 2,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [100] = 1,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
  [104] = 1,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
  [108] = 1,
    ACTIONS(31), 1,
      anon_sym_LPAREN,
  [112] = 1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
  [116] = 1,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
  [120] = 1,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
  [124] = 1,
    ACTIONS(39), 1,
      anon_sym_COMMA,
  [128] = 1,
    ACTIONS(41), 1,
      anon_sym_RPAREN,
  [132] = 1,
    ACTIONS(43), 1,
      anon_sym_RBRACE,
  [136] = 1,
    ACTIONS(45), 1,
      anon_sym_RBRACE,
  [140] = 1,
    ACTIONS(47), 1,
      anon_sym_GT,
  [144] = 1,
    ACTIONS(49), 1,
      anon_sym_RPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 14,
  [SMALL_STATE(4)] = 32,
  [SMALL_STATE(5)] = 44,
  [SMALL_STATE(6)] = 54,
  [SMALL_STATE(7)] = 64,
  [SMALL_STATE(8)] = 71,
  [SMALL_STATE(9)] = 78,
  [SMALL_STATE(10)] = 83,
  [SMALL_STATE(11)] = 90,
  [SMALL_STATE(12)] = 95,
  [SMALL_STATE(13)] = 100,
  [SMALL_STATE(14)] = 104,
  [SMALL_STATE(15)] = 108,
  [SMALL_STATE(16)] = 112,
  [SMALL_STATE(17)] = 116,
  [SMALL_STATE(18)] = 120,
  [SMALL_STATE(19)] = 124,
  [SMALL_STATE(20)] = 128,
  [SMALL_STATE(21)] = 132,
  [SMALL_STATE(22)] = 136,
  [SMALL_STATE(23)] = 140,
  [SMALL_STATE(24)] = 144,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_side_effects, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_side_effects_tail, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_taint_side_effect, 4, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_taint_side_effect, 6, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_taint_summary, 2, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_taint_summary, 3, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_side_effects_tail, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_side_effects, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_TaintSummary(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "TaintSummary",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
